// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[fileId].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/file/[key].ts";
import * as $4 from "./routes/api/file/index.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Canvas.tsx";
import * as $$1 from "./islands/Decryptor.tsx";
import * as $$2 from "./islands/Loader.tsx";
import * as $$3 from "./islands/VideoPlayer.tsx";

const manifest = {
  routes: {
    "./routes/[fileId].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/file/[key].ts": $3,
    "./routes/api/file/index.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Canvas.tsx": $$0,
    "./islands/Decryptor.tsx": $$1,
    "./islands/Loader.tsx": $$2,
    "./islands/VideoPlayer.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
