// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[fileId].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/file/[key].ts";
import * as $4 from "./routes/api/file/index.ts";
import * as $5 from "./routes/api/subscribe/index.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/stories/Icon.tsx";
import * as $8 from "./routes/stories/PhotopaperView.tsx";
import * as $9 from "./routes/stories/PhotopaperWrapper.tsx";
import * as $10 from "./routes/stories/_/Story.tsx";
import * as $11 from "./routes/stories/index.tsx";
import * as $$0 from "./islands/EmailSubscriptionInput.tsx";
import * as $$1 from "./islands/LeaveMail.tsx";
import * as $$2 from "./islands/Loader.tsx";
import * as $$3 from "./islands/MultiInput.tsx";
import * as $$4 from "./islands/PasswordForm.tsx";
import * as $$5 from "./islands/Photopaper/EffectSliders.tsx";
import * as $$6 from "./islands/Photopaper/PhotopaperBottomMenu.tsx";
import * as $$7 from "./islands/Photopaper/PhotopaperCanvas.tsx";
import * as $$8 from "./islands/Photopaper/PhotopaperTopMenu.tsx";
import * as $$9 from "./islands/Photopaper/PresetSelector.tsx";
import * as $$10 from "./islands/Photopaper/index.tsx";
import * as $$11 from "./islands/test_helpers/TestPhotopaperCanvas.tsx";

const manifest = {
  routes: {
    "./routes/[fileId].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/file/[key].ts": $3,
    "./routes/api/file/index.ts": $4,
    "./routes/api/subscribe/index.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/stories/Icon.tsx": $7,
    "./routes/stories/PhotopaperView.tsx": $8,
    "./routes/stories/PhotopaperWrapper.tsx": $9,
    "./routes/stories/_/Story.tsx": $10,
    "./routes/stories/index.tsx": $11,
  },
  islands: {
    "./islands/EmailSubscriptionInput.tsx": $$0,
    "./islands/LeaveMail.tsx": $$1,
    "./islands/Loader.tsx": $$2,
    "./islands/MultiInput.tsx": $$3,
    "./islands/PasswordForm.tsx": $$4,
    "./islands/Photopaper/EffectSliders.tsx": $$5,
    "./islands/Photopaper/PhotopaperBottomMenu.tsx": $$6,
    "./islands/Photopaper/PhotopaperCanvas.tsx": $$7,
    "./islands/Photopaper/PhotopaperTopMenu.tsx": $$8,
    "./islands/Photopaper/PresetSelector.tsx": $$9,
    "./islands/Photopaper/index.tsx": $$10,
    "./islands/test_helpers/TestPhotopaperCanvas.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
